### ISSUE TITLE
remove index.html from resources

### ISSUE THREAD

**Issue by saosebastiao** [jasongoodwin/authentikat-jwt#19]
The index.html file is being included with the jar distribution and it is overriding the index.html page in my play app.

**Comment by daniel-tcell** [comment]
+1 on this!

**Comment by jasongoodwin** [comment]
1.0.0-M1 is published which should fix this!
if you use the release please ping me back and let me know if you have any issues and I'll fix them asap.

**Comment by daniel-tcell** [comment]
@jasongoodwin damn that was fast! I'll try it out tonight and report back - thanks!

**Comment by daniel-tcell** [comment]
@jasongoodwin works like a charm! However I noticed that there is a few API changes in v1 and I read in the README that `When released, the API will contain additional methods to aid in validating different areas of the tokens.`. Do you have any plans on releasing those anytime soon? Right now its a bit messy to validate tokens using a `JwsVerifier` since we have to know about implementation details to know how to prepare the data argument to `apply(data: String, signatureData: String): Boolean`.

**Comment by jasongoodwin** [comment]
Thanks for the feedback. Ya the idea was to only allow certain types of
algorithms to be allowed by the verifier so people don't and a valid token
with no signature (algorithm = none) however there could be an implicit
list of acceptable algorithms too.

Let me look at this a bit more.

**Comment by daniel-tcell** [comment]
Sounds like a good idea to prevent verifying things without a signature :+1:

**Comment by daniel-tcell** [comment]
Btw, would it be possible for you to do a release of the old version but without index.html while this is still in progress?

**Comment by jasongoodwin** [comment]
Hey sorry I just saw this.
